#!/bin/bash
set -e

cabal exec cabal v2-run type-error-test/MissingField.hs 2>&1 | grep "Missing field 'f3' of 'TestRec'" > /dev/null
echo "missing field passed"

cabal exec cabal v2-run type-error-test/UnknownField.hs 2>&1 | grep "Unknown field 'f4' for 'TestRec'" > /dev/null
echo "unknown field passed"

cabal exec cabal v2-run type-error-test/IncorrectType.hs 2>&1 | grep -zo "Couldn't match type ‘\[Char]’ with ‘()’\s*arising from selecting the field ‘f3’" > /dev/null
echo "incorrect type passed"

cabal exec cabal v2-run type-error-test/IncorrectFunctor.hs 2>&1 | grep -zo "Couldn't match type: Maybe \[Char]\s*with: \[String]\s*arising from selecting the field ‘f3’" > /dev/null
echo "incorrect functor passed"

cabal exec cabal v2-run type-error-test/UnsatisfiedConstraint.hs 2>&1 | grep "No instance for (Show X) arising from a use of ‘show’" > /dev/null
echo "unsatisfied constraint passed"

cabal exec cabal v2-run type-error-test/InfiniteNesting.hs 2>&1 | grep "Unsupported type for HKD promotion: 'TestRec'" > /dev/null
echo "infinite nesting passed"

cabal exec cabal v2-run type-error-test/OutOfScopeDataCon.hs 2>&1 | grep "Data constructor must be in scope for HKD promotion: 'Record.MkR'" > /dev/null
echo "data con out of scope passed"

cabal exec cabal v2-run type-error-test/InScopeDataCon.hs
echo "data con in scope passed"

cabal exec cabal v2-run type-error-test/QualifiedImport.hs
echo "qualified import passed"
