name: CI

on:
  - push
  - pull_request

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.6.2.0"]
        ghc:
          - "9.2.5"
          - "9.4.2"
          - "9.6.1"

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2.0
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Update Cabal Index
      run: |
        cabal update

    - name: Configure
      run: |
        cabal configure --enable-tests --enable-documentation --test-show-details=direct --write-ghc-environment-files=always

    - name: Freeze
      run: |
        cabal freeze

    - uses: actions/cache@v3
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Install dependencies
      run: |
        cabal build --dependencies-only -j2 all
        cabal build --enable-tests --dependencies-only -j2 all

    - name: Build Without Tests
      run: |
        cabal build --disable-tests --disable-benchmarks all

    - name: Build
      run: |
        cabal build --enable-tests all

    - name: Test
      run: |
        cabal test --enable-tests all

    - name: Check
      run: |

    - name: Documentation
      run: |
        cabal haddock
